# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "regional-demand-app"
client_id = "18d43466cfc3fe70e1a062ddcda2e267"
application_url = "https://derived-roof-raw-incidents.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://derived-roof-raw-incidents.trycloudflare.com/auth/callback",
  "https://derived-roof-raw-incidents.trycloudflare.com/auth/shopify/callback",
  "https://derived-roof-raw-incidents.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6c10ea49.myshopify.com"
